
# Configuration file for the Flash C++ documentation generator.
# https://github.com/freod-sdk/flash

[project]
name = "Freod"
version = "" # dont bother
repository = "https://github.com/freod-sdk/freod"
tree = "https://github.com/freod-sdk/freod/tree/main"
icon = "loader/resources/logos/freod-circle.png"

[tutorials]
dir = "docs"
assets = [
    "docs/assets/*.png",
    "docs/assets/settings/*.png",
    "docs/assets/handbook/vol1/*.png",
    "docs/assets/handbook/vol2/*.png",
]

[[external-libs]]
pattern = "matjson"
repository = "https://github.com/freod-sdk/json"

[[external-libs]]
pattern = "Result.hpp"
repository = "https://github.com/freod-sdk/result"

[[sources]]
name = "Freod"
dir = "loader/include"
include = [
    "Freod/**/*.hpp",
    "Freod/**/*.h",
]
exclude = [
    "Freod/modify/Comparer.hpp",
    "Freod/platform/*.hpp",
    "Freod/c++stl/*.hpp",
    # All of the relevant cocos headers are included through Freod headers
    "Freod/cocos/**/*.h"
]

[[sources]]
name = "Bindings"
dir = "build-docs/bindings/bindings"
include = [
    "Freod/binding/*.hpp"
]
# Bindings are generated at compile time
exists-online = false

[ignore]
patterns-name = [
    # anything that starts with a double underscore
    # shouldnt be included
    "^__",
    "^tinyxml2$",
    "^format_as$",
    # operator overloads
    "^operator\\W"
]
patterns-full = [
    "^freod::modifier",
    "^freod::prelude",
    "^freod::stl",
    "^freod::freod_internal"
]

# CMake options

[cmake]
config-args = [
    "-G", "Ninja",
    "-DCMAKE_CXX_COMPILER=Clang",
    "-DCMAKE_C_COMPILER=Clang",
    "-DFREOD_BUILDING_DOCS=On",
    "-DFREOD_PLATFORM_NAME=Win64",
    "-DFREOD_CODEGEN_CMAKE_ARGS=-DCMAKE_CXX_COMPILER=Clang;-DCMAKE_C_COMPILER=Clang",
    "-DWIN32=On"
]
build-dir = "build-docs"

# The file we use to get all the include paths and such
infer-args-from = "loader/src/load.cpp"

[[scripts.css]]
name = "default.css"
content = "docs/flash-template/default.css"

[[scripts.css]]
name = "nav.css"
content = "docs/flash-template/nav.css"

[[scripts.css]]
name = "content.css"
content = "docs/flash-template/content.css"

[[scripts.css]]
name = "themes.css"
content = "docs/flash-template/themes.css"