name: Draft Release

on:
  workflow_dispatch:

jobs:
  draft:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Development Release
        uses: robinraju/release-downloader@v1.9
        with:
          tag: nightly
          fileName: '*'
          tarBall: false
          zipBall: true
          out-file-path: 'dev'

      - name: Declare Version Variable
        id: ref
        shell: bash
        run: |
          VERSION=$(unzip -p ${{ github.workspace }}/dev/freod-nightly.zip freod-sdk-freod-*/VERSION | xargs)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # test if release already exists
          set +e
          curl --fail "https://api.github.com/repos/freod-sdk/freod/releases/tags/v$VERSION" --silent --output /dev/null
          RESULT=$?
          set -e
          
          if [ $RESULT -eq 0 ]; then
            echo "Release $VERSION already exists! Not replacing it.."
            exit 1
          fi

      - name: Move Files
        run: |
          mv dev/freod-installer-*-win.exe freod-installer-v${{ steps.ref.outputs.version }}-win.exe
          mv dev/freod-installer-*-mac.pkg freod-installer-v${{ steps.ref.outputs.version }}-mac.pkg
          mv dev/freod-*-win.zip freod-v${{ steps.ref.outputs.version }}-win.zip
          mv dev/freod-*-mac.zip freod-v${{ steps.ref.outputs.version }}-mac.zip
          mv dev/freod-*-android32.zip freod-v${{ steps.ref.outputs.version }}-android32.zip
          mv dev/freod-*-android64.zip freod-v${{ steps.ref.outputs.version }}-android64.zip
          mv dev/resources.zip resources.zip

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.ref.outputs.version }}
          name: Freod v${{ steps.ref.outputs.version }}
          body: |
            TODO before publishing:
             - mark if pre-release
             - add changelog
             - remove this
          draft: true
          files: |
            ./freod-installer-v${{ steps.ref.outputs.version }}-win.exe
            ./freod-installer-v${{ steps.ref.outputs.version }}-mac.pkg
            ./freod-v${{ steps.ref.outputs.version }}-win.zip
            ./freod-v${{ steps.ref.outputs.version }}-mac.zip
            ./freod-v${{ steps.ref.outputs.version }}-android32.zip
            ./freod-v${{ steps.ref.outputs.version }}-android64.zip
            ./resources.zip
